version: "3.3"

volumes:
  sense-client-files:

services:

  qix:
    image: qlik/engine
    restart: always
    container_name: engine
    command: -S LockD=65522 -S DocumentDirectory=/documents -S ExtensionsDirectory=/extensions -S --WsPath /client --MigrationPort -1
    volumes:
      - ./example:/documents
      - sense-client-files:/client
      - ./build/dev:/extensions
    ports:
      - "9076:9076"
    depends_on:
      - sense-client

  sense-client:
    image: qlik/sense-client:4.58.5
    container_name: sense_client
    volumes:
      - sense-client-files:/client
    tty: true
